package PaymentGateway;

import java.io.IOException;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

//import com.opencsv.exceptions.CsvValidationException;


public class TestNGdemo {
	
		// Create an instance of the PaymentGatewayKeywords class
		PaymentGatewayKeywords pgKeywords = new PaymentGatewayKeywords();

		//public static void main(String[] args) throws IOException, InterruptedException  {
		// TODO Auto-generated method stub
		
		
		@Before
		public void SetUpTest() {
			pgKeywords.runTestStart();
			System.out.println("starting");
			
		}
		
		@Test
		public void RunTest() throws IOException, InterruptedException {
		
			//pgKeywords.runTestAutoGeneratedData();
			System.out.println("test");
			//pgKeywords.runTestStart();
			pgKeywords.runTestAlert();
			//pgKeywords.cleanup();
			//pgKeywords.runTestReadFromFile();
		
		}
		
		@After
		public void TearDownTest() throws IOException, InterruptedException {
			System.out.println("ending");
			pgKeywords.cleanup();
		}
		
	

}
